version: '3.9'

services:
  database:
    image: "container-registry.oracle.com/database/enterprise"
    container_name: oracle-MPLIST
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: YourPassword123
  #    volumes:
  #      - ./data:/opt/oracle/oradata
  redis:
    image: "redis:latest"
    container_name: redis_VTS
    ports:
      - "6379:6379"
