server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    username: system
    password: YourPassword123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

#  datasource:
#    url: jdbc:mysql://${DB_HOST:localhost}:3307/productserviceDb
#    username: root
#    password: root
#    driverClassName: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
  application:
    name: PRODUCT-SERVICE